apiVersion: v1
kind: Service
metadata:
  name: backend  # Your service name
  namespace: backend  # Your namespace
spec:
  type: LoadBalancer  # Set the type to LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend  # Make sure this matches your deployment label
