apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: frontend  # Update to your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/hardy-tine-435523-b0/backend
        ports:
        - containerPort: 80
        # You can include additional configurations here if needed.
